commitizen:
  # === ФОРМАТ КОММИТОВ ===
  name: cz_conventional_commits
  version_provider: scm
  version_scheme: semver
  style:
    - - qmark
      - fg:#ff9d00 bold
    - - question
      - bold
    - - answer
      - fg:#ff9d00 bold
    - - pointer
      - fg:#ff9d00 bold
    - - highlighted
      - fg:#ff9d00 bold
    - - selected
      - fg:#cc5454
    - - separator
      - fg:#cc5454
    - - instruction
      - ""
    - - text
      - ""
    - - disabled
      - fg:#858585 italic

  # === ВЕРСИОНИРОВАНИЕ ===
  major_version_zero: true
  tag_format: "v$version"

  # === CHANGELOG ===
  update_changelog_on_bump: true
  changelog_file: "CHANGELOG.md"
  changelog_format: "md"
  changelog_incremental: false

  # === СООБЩЕНИЕ ПРИ ОБНОВЛЕНИИ ВЕРСИИ ===
  bump_message: "chore(release): v$current_version -> v$new_version"

  # === ПРОВЕРКА КОММИТОВ ===
  check_commit_message: true
  min_message_length: 10
  max_message_length: 72